<?php

/**
 * @file
 * Empty on purpose.
 *
 * This file exists as a workaround for a problem: 
 * all module files are named cviews_block_filter_block.xyz, but they live
 * inside a views_block_exposed_filter_block folder (but no matching views_block_exposed_filter_block.info and
 * views_block_exposed_filter_block.module files).
 * See https://github.com/backdrop-contrib/views_block_exposed_filter_block/issues/1
 */
